### ISSUE TITLE
Can not open user_manual.pdf.

### ISSUE THREAD

**Issue by IamMegatron2025** [ignaciorlando/fundus-vessel-segmentation-tbme#1]
Hello, I am very interested in your tbme. But I can not open the user_manual.pdf. What has gone wrong?

**Comment by ignaciorlando** [comment]
Hi! Thanks for your warning. I've already pushed a newer version of the code where the user_manual is working. Don't hesitate in contact me if you have any doubt about how to use the code!

**Comment by IamMegatron2025** [comment]
@ignaciorlando  Thank you very much.
