### ISSUE TITLE
Error quadprog

### ISSUE THREAD

**Issue by ai1361720220000** [ignaciorlando/fundus-vessel-segmentation-tbme#10]
Hello Orlando, i just worked out your red lesion project, thanks!
But when i run this vessel segmentation code, there are some errors i can't solve. Could you help me?

Error quadprog (line 189)
   The 'active-set' algorithm has been removed from quadprog. To avoid this error, choose a different algorithm: 'interior-point-convex' or 'trust-region-reflective'.
Error  sosvm (line 35)
   state = bundler(state, phi,b, false);

Error sosvmCallback (line 39)
    [model, config, state] =sosvm(config, patterns, labels);

Error learnCRFPotentials (line 25)
        [bestModel, bestParam, state] = sosvmCallback(config, trainingdata);

Error learnConfiguredCRF (line 42)
    [model, qualityOverValidation,config] =learnCRFPotentials(config,trainingdata, validationdata);

Then i use 'trust-region-reflective' But other errors pop out.

**Comment by ignaciorlando** [comment]
Hi again!

Some questions:
- Which version of MATLAB are you using?
- Which errors are you getting when using 'trust-region-reflective'?
- Have you tried by removing the algorithm parameter from quadprog?

Cheers,

Nacho

**Comment by mumuaktar** [comment]
hi,
when I run the code, an error is showing: Index exceeds array bounds.

it is showing:   Error in extractFeatures (line 45)
                      dimensionality = size(features{1}, 2);
Would you please solve the issues?

Can I use the code for 3D medical imaging?

**Comment by ignaciorlando** [comment]
Hi @mumuaktar,
Unfortunately not, this code is only intended for 2D images.
Best,
Nacho

**Comment by mumuaktar** [comment]
hi,
when I run the code, an error is showing: Index exceeds array bounds.

it is showing: Error in extractFeatures (line 45)
dimensionality = size(features{1}, 2);
Would you please solve the issues? I used your dataset
