### ISSUE TITLE
Doing the command ' mex ./CRF/CRF_1.0/pairwisePart.cpp ./CRF/CRF_1.0/densecrf.cpp ./CRF/CRF_1.0/util.cpp' failed.

### ISSUE THREAD

**Issue by IamMegatron2025** [ignaciorlando/fundus-vessel-segmentation-tbme#2]
Hello, when I compile the Fully Connected CRF wrapper, doing the comand 'mex ./CRF/CRF_1.0/fullyCRFwithGivenPairwises.cpp ./CRF/CRF_1.0/densecrf.cpp ./CRF/CRF_1.0/util.cpp' work，but the command ' mex ./CRF/CRF_1.0/pairwisePart.cpp ./CRF/CRF_1.0/densecrf.cpp ./CRF/CRF_1.0/util.cpp' failed. The version of my matlab is R2014a. What should I do?

**Comment by ignaciorlando** [comment]
Try this out:
mex .\CRF\CRF_1.0\pairwisePart.cpp .\CRF\CRF_1.0\util.cpp

**Comment by IamMegatron2025** [comment]
@ignaciorlando  That works.Thank you.  I want to run your code in ubuntu, so I still need to compile './Features/Features/BCOSFIRE/COSFIRE/dilateDisc.c' using mex. But as I just know your paper and I do not know the inner function of dilateDisc.c, so how I compile the dilateDisc.c using mex?

**Comment by ignaciorlando** [comment]
That is part of an external code package by Azzopardi et al., that we used in another paper. You can run our code without even using that feature. If you want to use it as in our TBME paper, you just have to set Nguyen and Soares as the unary features and Zana as the pairwise.
