### ISSUE TITLE
Field assignment to a non-structure array object.

### ISSUE THREAD

**Issue by soulnd** [ignaciorlando/fundus-vessel-segmentation-tbme#6]
I set up the DRIVE dataset according the user_manual . Then I run the script_experiments_massive.m, the error occurs:
Field assignment to a non-structure array object.

Error in runVesselSegmentation (line 36)
        [model, config.qualityOverValidation, config] = learnConfiguredCRF(trainingdata, validationdata,
        config);

Error in script_experiments_massive (line 41)
        results{experiment,crfver} = runVesselSegmentation(config);

And I have another question:
My dataset don't have binary ground truth masks of the vessels, so how can I use your model to segment the vessels of my dataset?

**Comment by ignaciorlando** [comment]
Hi @soulnd 

I've pushed a newer version of the repository without that bug. Would you mind to verify if it solved your problem?

Please, remember to set the variable thereAreLabelsInTheTestData in false for your data set without ground truth labels.

Cheers,

Nacho

**Comment by soulnd** [comment]
I run the new version and the original problem is solved. But the new error occurs:

Subscripted assignment dimension mismatch.

Error in learnCRFPotentials>findBestC (line 77)
            qualitiesOnValidationSet(:, count) = averageMeasures.qualities;

Error in learnCRFPotentials (line 16)
        [bestModel, qualityOverValidation, bestParam, ~] = findBestC(config, trainingdata, validationdata,
        better);

Error in learnConfiguredCRF (line 42)
    [model, qualityOverValidation, config] = learnCRFPotentials(config, trainingdata, validationdata);

Error in runVesselSegmentation (line 36)
        [model, qualityOverValidation, config] = learnConfiguredCRF(trainingdata, validationdata, config);

Error in script_experiments_massive (line 41)
        results{experiment,crfver} = runVesselSegmentation(config);

**Comment by hsiaoma** [comment]
I ran into the same problem as @souInd. It seems that averageMeasures.qualities returns zeros(7,1). When I modified qualitiesOnValidationSet(:, count) to a (7,4) array instead of (8,4), Another problem occured.

Reference to non-existent field 'fMeasure'。

Error in getfield (line 36)
    f = s.(deblank(strField)); % deblank field name

Error in learnCRFPotentials>findBestC (line 100)
            currentQuality = getfield(averageMeasures, config.modelSelectionMetric);

Error in learnCRFPotentials (line 16)
        [bestModel, qualityOverValidation, bestParam, ~] = findBestC(config, trainingdata, validationdata, better);

Error in learnConfiguredCRF (line 42)
    [model, qualityOverValidation, config] = learnCRFPotentials(config, trainingdata, validationdata);

Error in runVesselSegmentation (line 36)
        [model, qualityOverValidation, config] = learnConfiguredCRF(trainingdata, validationdata, config);

Error in script_experiments_massive (line 42)
        results{experiment,crfver} = runVesselSegmentation(config);

**Comment by ignaciorlando** [comment]
Hi all!

Would you mind to check again now? In my laptop is working well.

Cheers,

Nacho

**Comment by soulnd** [comment]
I run the version you committed recently and it works! Thanks a lot!

**Comment by ignaciorlando** [comment]
Great!
