### ISSUE TITLE
Some problems about the source code

### ISSUE THREAD

**Issue by Author123456** [ignaciorlando/fundus-vessel-segmentation-tbme#9]
Hi Nacho,
It's my first message to a scientist, and I am so excited, and hope to get your reply.

Recently I am studying your paper, which really benefits me.
I also read the paper (Retinal Vessel Segmentation Using the 2-D Gabor
Wavelet and Supervised Classification 2006), and I find your source code also refers some code from the paper. Here I want to know how to get the source code of the paper (2006)? Would you like to give me a link? I want to study further.
Thank you a lot.

David

**Comment by ignaciorlando** [comment]
Hi David,

Thanks for your interest! You will find the implementation of the 2-D Gabor Wavelet here: https://github.com/ignaciorlando/fundus-vessel-segmentation-tbme/blob/master/Features/Features/Soares2006.m

Best,

Nacho

**Comment by Author123456** [comment]
Hi Nacho,

Thank your your reply!
The code is just about 2-D Gabor Wavelet, and could you share more code about the classifying the vessel in the paper, or the whole source code of the paper. (The original link the author provided is somehow invalid.)

Thank you.

Best,

David
